### ISSUE TITLE
Prevent Invalid input 

### ISSUE THREAD

**Issue by wre9-tesh** [DevBas-ed/Guess-the-number#14]
Players shouldn't be able to add Negative numbers and numbers above 20

# Screenshot

![image](https://user-images.githubusercontent.com/96977189/194395989-885056a2-c880-436c-bda4-47e9c7c09f93.png)
![image](https://user-images.githubusercontent.com/96977189/194396017-fa4f6ae6-85a7-4698-b09d-3606c6591b6b.png)

**Comment by wre9-tesh** [comment]
assign me this issue

**Comment by DevBas-ed** [comment]
Hi I have assigned you to this issue.
Best of Luck!
