### ISSUE TITLE
Fix Responsivity for all screens

### ISSUE THREAD

**Issue by Ritika-Agrawal811** [DevBas-ed/Guess-the-number#2]
May I fix responsivity for this project?

**Comment by DevBas-ed** [comment]
That would be great Ritika! 
You may.

**Comment by wre9-tesh** [comment]
@Ritika-Agrawal811  are u still working on this?

**Comment by Ritika-Agrawal811** [comment]
> @Ritika-Agrawal811 are u still working on this?

Yes will be completed by tomorrow
